name: Release on Main Push with Tagging

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare release folder (named ic3d_lib)
        run: |
          mkdir ic3d_lib
          cp -r dist ic3d_lib/
          cp fxmanifest.lua ic3d_lib/

      - name: Archive release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'ic3d_lib.zip'
          path: 'ic3d_lib'

      - name: Get version from package.json
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Get last commit message
        id: get_commit
        run: echo "msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Create tag if it doesn't exist
        run: |
          VERSION="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists."
          else
            echo "Creating tag $VERSION..."
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag "$VERSION"
            git push origin "$VERSION"
          fi

      - name: Create GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: "v${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          body: ${{ steps.get_commit.outputs.msg }}
          artifacts: ic3d_lib.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
